# Generated by Django 4.2.7 on 2023-11-06 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdentity',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_gender', models.CharField(max_length=1)),
                ('patient_birthday', models.DateField()),
                ('patient_phone_number', models.CharField(max_length=15)),
                ('patient_main_address', models.TextField()),
                ('patient_detail_address', models.TextField()),
                ('patient_residence_number', models.CharField(max_length=8)),
            ],
        ),
    ]
