# Generated by Django 4.2.7 on 2023-12-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientchart',
            name='image_title',
        ),
    ]
