# Generated by Django 4.2.7 on 2023-11-07 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPersonIdentity',
            fields=[
                ('medical_person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_person_name', models.CharField(max_length=60)),
                ('medical_person_gender', models.CharField(max_length=1)),
                ('medical_person_birthday', models.DateField()),
                ('medical_person_phone_number', models.CharField(max_length=15, null=True)),
                ('medical_person_main_address', models.TextField()),
                ('medical_person_detail_address', models.TextField()),
                ('medical_person_license', models.TextField()),
            ],
        ),
    ]
