# Generated by Django 4.2.7 on 2023-12-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlist',
            name='patient_name',
        ),
    ]
