# Generated by Django 4.2.7 on 2023-11-07 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_medicalpersonidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInbody',
            fields=[
                ('inbody_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('muscle_mass', models.FloatField()),
                ('body_fat_mass', models.FloatField()),
                ('total_body_water', models.FloatField()),
                ('protein', models.FloatField()),
                ('minerals', models.FloatField()),
                ('bmi', models.FloatField()),
                ('percent_body_fat', models.FloatField()),
                ('right_arm', models.FloatField()),
                ('left_arm', models.FloatField()),
                ('trunk', models.FloatField()),
                ('right_leg', models.FloatField()),
                ('left_leg', models.FloatField()),
                ('ecw_ratio', models.FloatField()),
                ('record_date', models.DateField()),
                ('original_file_location', models.BinaryField()),
                ('medical_person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.medicalpersonidentity')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.patientidentity')),
            ],
        ),
    ]
