# Generated by Django 4.2.7 on 2023-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_remove_patientlist_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='patient_type',
            field=models.CharField(choices=[('일반환자', '일반환자'), ('중증환자', '중증환자'), ('VIP', 'VIP')], max_length=10),
        ),
    ]
