# Generated by Django 4.2.7 on 2023-12-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_remove_patientchart_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinbody',
            name='ecw_ratio',
        ),
        migrations.RemoveField(
            model_name='patientinbody',
            name='minerals',
        ),
        migrations.RemoveField(
            model_name='patientinbody',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='patientinbody',
            name='total_body_water',
        ),
        migrations.AlterField(
            model_name='patientinbody',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
