# Generated by Django 4.2.7 on 2023-12-05 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_alter_patientlist_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientexamination',
            name='diagnosis_prescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patientexamination',
            name='examination_detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patientexamination',
            name='medical_person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.medicalpersonidentity'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_title', models.TextField(default='a.jpg', null=True)),
                ('image_url', models.ImageField(upload_to='uploaded_pictures')),
                ('image_context', models.TextField(default='a')),
                ('image_date', models.DateTimeField()),
                ('examination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patientexamination')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
