# Generated by Django 4.2.7 on 2023-12-16 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_remove_patientinbody_medical_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBlood',
            fields=[
                ('blood_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hemoglobin', models.FloatField(verbose_name='혈색소')),
                ('fasting_blood_sugar', models.FloatField(verbose_name='공복혈당')),
                ('total_cholesterol', models.FloatField(verbose_name='총 콜레스트롤')),
                ('hdl_cholesterol', models.FloatField(verbose_name='HDL-콜레스트롤')),
                ('triglycerides', models.FloatField(verbose_name='중성지방')),
                ('ldl_cholesterol', models.FloatField(verbose_name='LDL-콜레스트롤')),
                ('serum_creatinine', models.FloatField(verbose_name='혈청크레아티닌')),
                ('glomerular_filtration_rate', models.FloatField(verbose_name='신사구체여과율')),
                ('ast', models.FloatField(verbose_name='AST')),
                ('alt', models.FloatField(verbose_name='ALT')),
                ('gamma_gt', models.FloatField(verbose_name='감마지피티')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.patientidentity')),
            ],
        ),
    ]
