# Generated by Django 4.2.7 on 2023-12-14 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_remove_medicalpersonidentity_medical_person_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientexamination',
            name='examination_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PatientReception',
            fields=[
                ('reception_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_reason', models.TextField()),
                ('reception_date', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patientidentity')),
            ],
            options={
                'db_table': 'patient_reception',
            },
        ),
    ]
