# Generated by Django 4.2.7 on 2023-12-16 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_patientblood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50, unique=True)),
                ('disease_name', models.CharField(max_length=200)),
                ('disease_description', models.TextField()),
            ],
            options={
                'verbose_name': '질병',
                'verbose_name_plural': '질병들',
            },
        ),
        migrations.CreateModel(
            name='InspectType',
            fields=[
                ('inspect_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspect_type', models.CharField(max_length=50, verbose_name='검사 종류')),
                ('inspect_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('medication_name', models.CharField(max_length=200)),
                ('medication_type', models.CharField(max_length=100)),
                ('medication_description', models.TextField()),
                ('administration_method', models.CharField(max_length=100)),
                ('medication_cost', models.IntegerField()),
            ],
            options={
                'verbose_name': '약물',
                'verbose_name_plural': '약물들',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('treatment_name', models.CharField(max_length=200)),
                ('treatment_cost', models.IntegerField()),
            ],
            options={
                'verbose_name': '치료',
                'verbose_name_plural': '치료들',
            },
        ),
        migrations.RemoveField(
            model_name='patientchart',
            name='prescription',
        ),
        migrations.CreateModel(
            name='Inspect',
            fields=[
                ('inspect_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='검사 ID')),
                ('inspect_content', models.TextField(verbose_name='검사 내용')),
                ('inspect_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.inspecttype')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patientidentity')),
            ],
            options={
                'db_table': 'inspect',
            },
        ),
        migrations.AddField(
            model_name='patientchart',
            name='disease',
            field=models.ManyToManyField(related_name='charts', to='emr.disease'),
        ),
        migrations.AddField(
            model_name='patientchart',
            name='inspect',
            field=models.ManyToManyField(related_name='charts', to='emr.inspecttype'),
        ),
        migrations.AddField(
            model_name='patientchart',
            name='medication',
            field=models.ManyToManyField(related_name='charts', to='emr.medication'),
        ),
        migrations.AddField(
            model_name='patientchart',
            name='treatment',
            field=models.ManyToManyField(related_name='charts', to='emr.treatment'),
        ),
    ]
