# Generated by Django 4.2.7 on 2023-12-16 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_disease_inspecttype_medication_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspect',
            name='inspect_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inspect',
            name='inspect_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
