# Generated by Django 4.2.7 on 2023-12-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_alter_patientreception_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreception',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patientreception',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='emr.patientidentity'),
        ),
    ]
