# Generated by Django 4.2.7 on 2023-12-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_inspect_inspect_date_alter_inspect_inspect_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Disease', 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': '약물', 'verbose_name_plural': 'Medication'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatments'},
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment_id',
            new_name='treatment_code',
        ),
        migrations.AlterField(
            model_name='medication',
            name='administration_method',
            field=models.TextField(),
        ),
    ]
