# Generated by Django 5.0 on 2023-12-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0007_customuser_medicalprofessional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalprofessional",
            name="classification_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="emr.classificationcode"
            ),
        ),
    ]
